global:
  smtp_smarthost: smtp.email.com:587
  smtp_from: noreply@email.com
  smtp_auth_username: noreply@email.com
  smtp_auth_password: suaSenhaAqui

route:
  group_by: ['alertname']
  group_interval: 5m
  group_wait: 30s
  receiver: 'email'
  repeat_interval: 3h

receivers:

  - name: 'email'
    email_configs:
    - to: alert@gmail.com
      send_resolved: true